config-version: 2

name: "deel_dbt"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 275557 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  deel_dbt:
    seeds:
      +schema: "raw"

models:
  deel_dbt:
    staging:
      +materialized: view
      +schema: "staging"
    marts:
      +materialized: table
      +schema: "marts"
